apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tom
  name: tom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tom
    spec:
      containers:
      - image: lukeshgadge/lukesh
        name: tomcat
        ports:
        - containerPort: 8080
        resources: {}
status: {}
